version: "3.8"

services:
  ip-geolocation:
    build: .
    ports:
      - "3500:3500"
    environment:
      NODE_ENV: production 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"